[package]
name = "als_parser_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.8"
quick-xml = "0.38.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
